import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/component/Providers"; 
import logo from '../../assets/6220ca7c-2f6c-465b-850f-16fe86b063d3_16x9_1200x676.webp';
import logo1 from '../../assets/download-removebg-preview.png';
import Image from "next/image";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      style={{
        backgroundImage: `url(${logo.src})`,
        backgroundSize: 'cover',
        backgroundRepeat: 'no-repeat',
        backgroundPosition: 'center',
        width: '100%', 
        height: '100%', 
      }}
        className={`${geistSans.variable} ${geistMono.variable}  antialiased `}
      >
        <Providers>
           <div className="flex flex-col  w-full items-center">
            <Link
            className="  self-end p-2 rounded-xl m-4"
            href='/'>
           
            <Image
            src={logo1}
            alt="logo1"
            className='size-[70px] p-1 bg-white rounded-xl '
          />
            </Link>              
            {children}  

           </div>
            
        </Providers>
      </body>
    </html>
  );
}
