import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navpar from "@/component/Navpar";
import Fotter from "@/component/Fotter";
import Whatsappicon from "@/component/Whatsappicon";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-r from-gray-100 via-gray-200 to-gray-100




`}
      > 
      <div className="flex flex-col items-center  justify-between  w-full h-screen">

       <Navpar path="/" />
        {children}
        <div className="relative w-full">
        <Fotter/>
        <div className="absolute bottom-[20px] right-[20px]">
        <Whatsappicon/>
        </div>
        </div>
      </div>

    
      
      </body>
    </html>
  );
}
